[build]
  publish = "build/web"
  command = "curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.4-stable.tar.xz && tar xf flutter_linux_3.38.4-stable.tar.xz && export PATH=`pwd`/flutter/bin:$PATH && flutter --version && rm lib/main.dart && cp lib/web_main.dart lib/main.dart && flutter build web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
